export enum UserRole {
  ADMIN = 'ADMIN',
  BUYER = 'BUYER',
  SUPPLIER = 'SUPPLIER',
}

export enum ActorType {
  SYSTEM = 'SYSTEM',
  ADMIN = 'ADMIN',
  BUYER = 'BUYER',
  SUPPLIER = 'SUPPLIER',
}

export enum AuditEventType {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  SUPPLIER_ONBOARDED = 'SUPPLIER_ONBOARDED',
  RFQ_CREATED = 'RFQ_CREATED',
  RFQ_PUBLISHED = 'RFQ_PUBLISHED',
  SUPPLIER_ACCEPTED = 'SUPPLIER_ACCEPTED',
  SUPPLIER_DECLINED = 'SUPPLIER_DECLINED',
  BID_SUBMITTED = 'BID_SUBMITTED',
  BID_REVISED = 'BID_REVISED',
  COMMERCIAL_LOCK = 'COMMERCIAL_LOCK',
  DEADLINE_EXTENDED = 'DEADLINE_EXTENDED',
  RFQ_CLOSED = 'RFQ_CLOSED',
  AWARD_SIMULATED = 'AWARD_SIMULATED',
  AWARD_FINALIZED = 'AWARD_FINALIZED',
  AWARD_FULFILLED = 'AWARD_FULFILLED',
  ADMIN_OVERRIDE = 'ADMIN_OVERRIDE',
  CONFIG_CHANGED = 'CONFIG_CHANGED',
  NEGOTIATION_CREATED = 'NEGOTIATION_CREATED',
  NEGOTIATION_CLOSED = 'NEGOTIATION_CLOSED',
  NEGOTIATION_AWARDED = 'NEGOTIATION_AWARDED',
}

export enum RFQStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  AWARDED = 'AWARDED',
}

export enum SupplierAssignmentStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
}

export enum CredibilityClass {
  EXCELLENT = 'EXCELLENT',
  STABLE = 'STABLE',
  RISKY = 'RISKY',
}

export enum RankColor {
  GREEN = 'GREEN',
  YELLOW = 'YELLOW',
  RED = 'RED',
}

export enum ProximityLabel {
  VERY_CLOSE = 'VERY_CLOSE',
  CLOSE = 'CLOSE',
  FAR = 'FAR',
}

export enum FlagType {
  DELIVERY_DEVIATION = 'delivery_deviation',
  PAYMENT_DEVIATION = 'payment_deviation',
  ABNORMAL_PRICE = 'abnormal_price',
  SUPPLIER_DOMINANCE = 'supplier_dominance',
  LATE_REVISIONS = 'late_revisions',
}

export enum NegotiationStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  AWARDED = 'AWARDED',
}

export enum NegotiationSupplierStatus {
  INVITED = 'INVITED',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
}
